In [5]:
import pandas as pd
import numpy as np

In [6]:
df=pd.read_csv("turbine_5yr_complex_data.csv")
df.head(3)

,timestamp,gearbox_oil_temp,gearbox_bearing_temp,vibration_x,vibration_y,vibration_z,oil_pressure,particle_count
0,2025-01-01 00:00:00,59.24,65.85,0.0109,0.0092,0.0130,4.53,100
1,2025-01-01 00:10:00,60.12,66.83,0.0076,0.0065,0.0092,4.48,100
2,2025-01-01 00:20:00,59.50,65.16,0.0160,0.0136,0.0193,4.53,100

In [7]:
df=df.drop("timestamp",axis=1)
df

,gearbox_oil_temp,gearbox_bearing_temp,vibration_x,vibration_y,vibration_z,oil_pressure,particle_count
0,59.24,65.85,0.0109,0.0092,0.0130,4.53,100
1,60.12,66.83,0.0076,0.0065,0.0092,4.48,100
2,59.50,65.16,0.0160,0.0136,0.0193,4.53,100
3,60.28,65.80,0.0164,0.0140,0.0197,4.54,100
4,60.72,66.84,0.0177,0.0151,0.0213,4.49,100
...,...,...,...,...,...,...,...
262795,61.80,87.31,0.0243,0.0206,0.0291,4.19,1413
262796,61.52,89.94,0.0287,0.0244,0.0345,4.23,1413
262797,60.97,86.79,0.0247,0.0210,0.0296,4.17,1413
262798,62.49,89.88,0.0184,0.0156,0.0221,4.22,1413
262799,62.05,87.55,0.0264,0.0225,0.0317,4.20,1413

In [8]:
from sklearn.ensemble import IsolationForest

In [9]:
import pandas as pd
from sklearn.preprocessing import StandardScaler,MinMaxScaler

In [10]:
df = pd.DataFrame({
    'Yas': [22, 45, 30, 50],
    'Gelir': [15000, 90000, 45000, 120000]
})

In [11]:
sclaer_std=StandardScaler()

In [13]:
df["Gelir_Standard"]=sclaer_std.fit_transform(df[["Gelir"]])

In [14]:
scaler_minmax=MinMaxScaler()
df["Gelir_MinMax"]=scaler_minmax.fit_transform(df[["Gelir"]])

In [15]:
df

   Yas   Gelir  Gelir_Standard  Gelir_MinMax
0   22   15000       -1.299867      0.000000
1   45   90000        0.557086      0.714286
2   30   45000       -0.557086      0.285714
3   50  120000        1.299867      1.000000

In [6]:
from sklearn.impute import SimpleImputer
import numpy as np
import pandas as pd

In [7]:
data = {
    'Yas': [22, 38, np.nan, 26, 35],           # 1 adet boş
    'Maas': [20000, 50000, 30000, np.nan, 45000],# 1 adet boş
    'Departman': ['IT', 'IK', 'IT', 'IK', np.nan] # 1 adet boş kategorik
}

In [8]:
df=pd.DataFrame(data)

In [10]:
num_imputer=SimpleImputer(strategy="median")
df[["Yas","Maas"]]=num_imputer.fit_transform(df[["Yas","Maas"]])
cat_imputer=SimpleImputer(strategy="most_frequent")
df[["Departman"]]=cat_imputer.fit_transform(df[["Departman"]])

In [11]:
df

    Yas     Maas Departman
0  22.0  20000.0        IT
1  38.0  50000.0        IK
2  30.5  30000.0        IT
3  26.0  37500.0        IK
4  35.0  45000.0        IK