In [27]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split,cross_val_score
# from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier

In [28]:
df=pd.read_csv("customer_booking.csv",encoding="latin-1")
df.head(3)

,num_passengers,sales_channel,trip_type,purchase_lead,length_of_stay,flight_hour,flight_day,route,booking_origin,wants_extra_baggage,wants_preferred_seat,wants_in_flight_meals,flight_duration,booking_complete
0,2,Internet,RoundTrip,262,19,7,Sat,AKLDEL,New Zealand,1,0,0,5.52,0
1,1,Internet,RoundTrip,112,20,3,Sat,AKLDEL,New Zealand,0,0,0,5.52,0
2,2,Internet,RoundTrip,243,22,17,Wed,AKLDEL,India,1,1,0,5.52,0

In [29]:
# kategorik_sutunlar=["booking_origin","route","flight_day","trip_type","sales_channel"]
# encoder_deposu={}

In [30]:
# for sutun in kategorik_sutunlar:
#     le=LabelEncoder()
#     df[sutun]=le.fit_transform(df[sutun])
#     encoder_deposu[sutun]=le

In [31]:
df

,num_passengers,sales_channel,trip_type,purchase_lead,length_of_stay,flight_hour,flight_day,route,booking_origin,wants_extra_baggage,wants_preferred_seat,wants_in_flight_meals,flight_duration,booking_complete
0,2,Internet,RoundTrip,262,19,7,Sat,AKLDEL,New Zealand,1,0,0,5.52,0
1,1,Internet,RoundTrip,112,20,3,Sat,AKLDEL,New Zealand,0,0,0,5.52,0
2,2,Internet,RoundTrip,243,22,17,Wed,AKLDEL,India,1,1,0,5.52,0
3,1,Internet,RoundTrip,96,31,4,Sat,AKLDEL,New Zealand,0,0,1,5.52,0
4,2,Internet,RoundTrip,68,22,15,Wed,AKLDEL,India,1,0,1,5.52,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,2,Internet,RoundTrip,27,6,9,Sat,PERPNH,Australia,1,0,1,5.62,0
49996,1,Internet,RoundTrip,111,6,4,Sun,PERPNH,Australia,0,0,0,5.62,0
49997,1,Internet,RoundTrip,24,6,22,Sat,PERPNH,Australia,0,0,1,5.62,0
49998,1,Internet,RoundTrip,15,6,11,Mon,PERPNH,Australia,1,0,1,5.62,0
49999,1,Internet,RoundTrip,19,6,10,Thu,PERPNH,Australia,0,1,0,5.62,0

In [32]:
df=pd.get_dummies(df,columns=["booking_origin","route","flight_day","trip_type","sales_channel"],drop_first=True)

In [33]:
y=df["wants_extra_baggage"]
x=df.drop("wants_extra_baggage",axis=1)

In [36]:
rf=RandomForestClassifier()

In [38]:
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=42,train_size=0.85)

In [39]:
model=rf.fit(x_train,y_train)
model.score(x_test,y_test)

0.7226666666666667

In [40]:
crossval=cross_val_score(model,x,y,cv=4)

In [41]:
crossval.mean()

np.float64(0.5000800000000001)

In [42]:
crossval.std()

np.float64(0.12103459340205179)

In [45]:
crossval

array([0.67128, 0.43192, 0.35024, 0.54688])