In [144]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer

In [145]:
df=pd.read_csv("banka.csv")
df.head(5)

                                      metin                 kategori
0        kart şifremi değiştirmek istiyorum  Kart Şifresi Değiştirme
1  kartımın şifresini değiştirmek istiyorum  Kart Şifresi Değiştirme
2          kredi kartımın şifresini unuttum  Kart Şifresi Değiştirme
3               kart şifremi hatırlamıyorum  Kart Şifresi Değiştirme
4              kart şifresi almak istiyorum  Kart Şifresi Değiştirme

In [146]:
mesaj=input("Lütfen yapmak istediğiniz işlemi giriniz.")
mesajdf=pd.DataFrame([{"metin":mesaj,"kategori":0}])
df=pd.concat([df,mesajdf,],ignore_index=True)
df["metin"]=df["metin"].str.lower()
df

                                           metin                 kategori
0             kart şifremi değiştirmek istiyorum  Kart Şifresi Değiştirme
1       kartımın şifresini değiştirmek istiyorum  Kart Şifresi Değiştirme
2               kredi kartımın şifresini unuttum  Kart Şifresi Değiştirme
3                    kart şifremi hatırlamıyorum  Kart Şifresi Değiştirme
4                   kart şifresi almak istiyorum  Kart Şifresi Değiştirme
...                                          ...                      ...
1156  konut kredisi uzmanıyla görüşmek istiyorum          Kredi Başvurusu
1157            kredi çekmek için ne yapmalıyım?          Kredi Başvurusu
1158             faizsiz ihtiyaç kredisi var mı?          Kredi Başvurusu
1159                  kredi başvurum ne durumda?          Kredi Başvurusu
1160            kredi kartımın şifresini unuttum                        0

[1161 rows x 2 columns]

In [147]:
x=df["metin"].iloc[0:-1]
y=df["kategori"].iloc[0:-1]
tahmin=df["metin"].iloc[-1]
tahmin

'kredi kartımın şifresini unuttum'

In [148]:
stop_words=['fakat','lakin','ancak','acaba', 'ama', 'aslında', 'az', 'bazı', 'belki', 'biri', 'birkaç', 'birşey', 'biz', 'bu', 'çok', 'çünkü', 'da', 'daha', 'de', 'defa', 'diye', 'eğer', 'en', 'gibi', 'hem', 'hep', 'hepsi', 'her', 'hiç', 'için', 'ile', 'ise', 'kez', 'ki', 'kim', 'mı', 'mu', 'mü', 'nasıl', 'ne', 'neden', 'nerde', 'nerede', 'nereye', 'niçin', 'niye', 'o', 'sanki', 'şey', 'siz', 'şu', 'tüm', 've', 'veya', 'ya', 'yani']
for word in stop_words:
    word=" "+word+" "
    df["metin"]=df["metin"].replace(word,"")

In [149]:
cv=CountVectorizer(max_features=50)
x=cv.fit_transform(df["metin"].iloc[0:-1]).toarray()
tahmin=cv.transform([df["metin"].iloc[-1]]).toarray()
x

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 1],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(1160, 50))

In [150]:
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=42,train_size=0.7)
rf=RandomForestClassifier()
model=rf.fit(x_train,y_train)
model.score(x_test,y_test)

0.8275862068965517

In [151]:
model.predict(tahmin)

array(['Kart Şifresi Değiştirme'], dtype=object)