In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler,MinMaxScaler

In [2]:
df=pd.read_csv("Plane Price.csv")

In [3]:
df.head(3)

,Model Name,Engine Type,HP or lbs thr ea engine,Max speed Knots,Rcmnd cruise Knots,Stall Knots dirty,Fuel gal/lbs,All eng rate of climb,Eng out rate of climb,Takeoff over 50ft,Landing over 50ft,Empty weight lbs,Length ft/in,Wing span ft/in,Range N.M.,Price
0,100 Darter (S.L. Industries),Piston,145,104,91.0,46.0,36,450,900.0,1300.0,"2,050","1,180",25/3,37/5,370,1300000.0
1,7 CCM Champ,Piston,85,89,83.0,44.0,15,600,720.0,800.0,"1,350",820,20/7,36/1,190,1230000.0
2,100 Darter (S.L. Industries),Piston,90,90,78.0,37.0,19,650,475.0,850.0,"1,300",810,21/5,35/0,210,1600000.0

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 517 entries, 0 to 516
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Model Name               517 non-null    str
 1   Engine Type              517 non-null    str
 2   HP or lbs thr ea engine  517 non-null    str
 3   Max speed Knots          497 non-null    str
 4   Rcmnd cruise Knots       507 non-null    float64
 5   Stall Knots dirty        502 non-null    float64
 6   Fuel gal/lbs             517 non-null    int64
 7   All eng rate of climb    513 non-null    str
 8   Eng out rate of climb    491 non-null    float64
 9   Takeoff over 50ft        492 non-null    float64
 10  Landing over 50ft        517 non-null    str
 11  Empty weight lbs         516 non-null    str
 12  Length ft/in             517 non-null    str
 13  Wing span ft/in          517 non-null    str
 14  Range N.M.               499 non-null    str
 15  Price                    507 non-null    float64
dtypes: float64(5), int64(1), str(10)
memory usage: 64.8 KB

In [11]:
df=df[["Rcmnd cruise Knots","Stall Knots dirty","Fuel gal/lbs","Eng out rate of climb","Price"]]
df=df.dropna()
df.head(3)

,Rcmnd cruise Knots,Stall Knots dirty,Fuel gal/lbs,Eng out rate of climb,Price
0,91.0,46.0,36,900.0,1300000.0
1,83.0,44.0,15,720.0,1230000.0
2,78.0,37.0,19,475.0,1600000.0

In [12]:
y=df["Price"]
x=df.drop(columns=["Price"])

Y için normalizasyon yapılmaz.
Outlier etkisini azaltır.
Model performansı artar.

In [13]:
ss=StandardScaler()
x2=ss.fit_transform(x)

In [14]:
np.mean(x2)

np.float64(3.475480772739621e-17)

In [15]:
df.info()

<class 'pandas.DataFrame'>
Index: 460 entries, 0 to 516
Data columns (total 5 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Rcmnd cruise Knots     460 non-null    float64
 1   Stall Knots dirty      460 non-null    float64
 2   Fuel gal/lbs           460 non-null    int64
 3   Eng out rate of climb  460 non-null    float64
 4   Price                  460 non-null    float64
dtypes: float64(4), int64(1)
memory usage: 21.6 KB