In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
df=pd.read_csv("student_lifestyle_100k.csv")

In [3]:
df.head(3)

,Student_ID,Age,Gender,Department,CGPA,Sleep_Duration,Study_Hours,Social_Media_Hours,Physical_Activity,Stress_Level,Depression
0,1001,22,Female,Science,3.50,7.3,3.3,3.4,114,5,False
1,1002,20,Male,Engineering,2.72,5.5,7.2,6.0,142,2,False
2,1003,20,Male,Medical,3.01,5.4,2.3,1.8,137,3,False

In [4]:
df=df.drop("Student_ID",axis=1)

In [6]:
df=pd.get_dummies(df,columns=["Gender","Department"])
df

,Age,CGPA,Sleep_Duration,Study_Hours,Social_Media_Hours,Physical_Activity,Stress_Level,Depression,Gender_Female,Gender_Male,Department_Arts,Department_Business,Department_Engineering,Department_Medical,Department_Science
0,22,3.50,7.3,3.3,3.4,114,5,False,True,False,False,False,False,False,True
1,20,2.72,5.5,7.2,6.0,142,2,False,False,True,False,False,True,False,False
2,20,3.01,5.4,2.3,1.8,137,3,False,False,True,False,False,False,True,False
3,21,3.63,8.1,2.0,4.6,130,3,False,False,True,False,False,True,False,False
4,19,3.14,6.8,2.6,4.3,4,6,False,False,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,24,2.02,7.0,0.6,1.4,66,4,False,True,False,False,False,False,True,False
99996,24,2.33,5.0,3.6,5.2,103,3,False,False,True,True,False,False,False,False
99997,24,2.23,6.5,5.8,4.1,61,5,False,True,False,False,False,True,False,False
99998,19,3.61,6.1,4.8,4.9,116,4,False,False,True,False,False,True,False,False
99999,24,2.10,7.9,3.5,4.0,79,4,False,True,False,False,False,False,True,False

In [7]:
y=df["Depression"]
x=df.drop("Depression",axis=1)

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=42,train_size=0.9)

In [10]:
from sklearn.ensemble import RandomForestClassifier

In [11]:
rf=RandomForestClassifier()

In [12]:
model=rf.fit(x_train,y_train)
model.score(x_test,y_test)

0.8990666666666667

In [13]:
y_pred=model.predict(x_test)

In [14]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[26900,    92],
       [ 2936,    72]])

In [18]:
dfs=pd.DataFrame()
dfs["sonuc"]=y_pred
dfs["sonuc"].value_counts()
dfs["gercek"]=y_test.values

In [19]:
y.info()

<class 'pandas.Series'>
RangeIndex: 100000 entries, 0 to 99999
Series name: Depression
Non-Null Count   Dtype
--------------   -----
100000 non-null  bool
dtypes: bool(1)
memory usage: 97.8 KB

In [20]:
dfs

       sonuc  gercek
0      False   False
1      False   False
2      False   False
3      False   False
4      False   False
...      ...     ...
29995  False   False
29996  False   False
29997  False   False
29998  False    True
29999  False   False

[30000 rows x 2 columns]

In [22]:
dfs["TrueBil"]=(dfs["gercek"]==True)& (dfs["sonuc"]==True)

In [23]:
dfs["TrueBil"].value_counts()

TrueBil
False    29928
True        72
Name: count, dtype: int64

In [24]:
from sklearn.metrics import precision_score

In [25]:
precision_score(dfs["gercek"],dfs["sonuc"])

0.43902439024390244

In [26]:
dfs['sonuc'].value_counts()

sonuc
False    29836
True       164
Name: count, dtype: int64

In [27]:
72/164

0.43902439024390244